### ISSUE TITLE
TypeError - "reading 'toString')

### ISSUE THREAD

**Issue by bradwrage** [MoralisWeb3/youtube-tutorials#23]
I'm getting the following error when running. 

TypeError: Cannot read properties of undefined (reading 'toString')

**Comment by princeofburma** [comment]
I have been trying to resolve the same error code.

**Comment by santosh7063** [comment]
same issue here.
TypeError: Cannot read properties of undefined (reading 'toString')

**Comment by ivan-liljeqvist** [comment]
Hey guys - please post in https://forum.moralis.io and explain exactly which code you run
